name = "SparseFactorizations"
uuid = "2e15f5d3-a4a2-4ab2-ae69-94e18afaa365"
authors = ["Simon Etter <ettersi@nus.edu.sg>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
